import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  viewUtama: {
    flex: 1,
  },
  viewHeader: {
    width: '100%',
    height: 40,
    backgroundColor: '#ffff',
    elevation: 5,
    justifyContent: 'center',
  },
  loginRegister: {
    width: '90%',
    height: 190,
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 90,
    marginLeft: 18,
    elevation: 10,
  },
  boxLoginRegister: {
    width: '40%',
    height: 50,
    margin: 5,
    borderRadius: 20,
  },
  viewScroll: {
    flex: 1,
    backgroundColor: '#3462f9',
  },
  tampilan: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    borderRadius: 50,
    alignSelf: 'center',
    top: 50,
  },
  BoxImage: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    borderRadius: 50,
    alignSelf: 'center',
    top: 50,
    borderWidth: 7,
    borderColor: '#3462f9',
    marginTop: -95,
    borderWidth: 7,
    margin: 5,
  },
  posisenLogin: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 80,
  },
  backView1: {
    width: '100%',
    height: 200,
    flexDirection: 'row',
    backgroundColor: '#dce9f9',
  },
  fotoProfile: {
    backgroundColor: 'white',
    width: 100,
    height: 100,
    top: 30,
    marginLeft: 15,
    borderRadius: 50,
    alignItems: 'center',
  },
  Image: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  backView2: {
    width: '95%',
    height: 300,
    alignSelf: 'center',
    backgroundColor: '#87CEFA',
    borderRadius: 15,
    top: -50,
    padding: 15,
    elevation: 5,
  },
  dataDiri: {
    flex: 1,
    marginLeft: 15,
    top: 50,
  },
  dataMember: {
    backgroundColor: 'white',
    width: 340,
    height: 50,
    alignItems: 'center',
    paddingLeft: 5,
    borderRadius: 5,
    flexDirection: 'row',
    elevation: 5,
    marginTop: 10,
  },
  dataText: {
    paddingLeft: 5,
  },
});
