import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  viewUtama: {
    flex: 1,
    width: '100%',
    height: 900,
  },
  viewHeader: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    elevation: 5,
    backgroundColor: 'white',
    paddingLeft: 5,
  },
  taksHeader: {
    fontSize: 20,
  },
  viewFoto: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 110,
    height: 110,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 15,
    elevation: 5,
    margin: 7,
    backgroundColor: 'white',
  },
  Image: {
    width: 110,
    height: 110,
    borderRadius: 10,
  },
  textImage: {
    width: 100,
    height: 100,
    backgroundColor: 'gray',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginVertical: 15,
  },
  viewText: {
    width: '90%',
    height: 690,
    backgroundColor: '#87CEFA',
    borderRadius: 10,
    marginLeft: 20,
    marginVertical: 17,
    elevation: 5,
  },
  viewInput: {
    // backgroundColor: 'red',
    marginTop: 5,
    marginLeft: 5,
  },
  boxInput: {
    width: '90%',
    height: 40,
    backgroundColor: '#F0F8FF',
    marginTop: 5,
    marginLeft: 15,
    borderRadius: 10,
    paddingLeft: 15,
  },
  klikTambah: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22b922',
    borderRadius: 25,
    width: '50%',
    alignSelf: 'center',
    marginTop: 35,
    height: 40,
  },
  textTambah: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#fcf8f8',
  },
});
